name: 'bank_statements'
version: '1.0.0'
config-version: 2

profile: 'bank_statements'

model-paths: ["models"]
seed-paths: ["seeds"]

models:
  bank_statements:
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    marts:
      +materialized: table

seeds:
  bank_statements:
    category_keywords:
      +column_types:
        priority: INT64
        category: STRING
        keyword: STRING
        requires_credit: BOOL
